### ISSUE TITLE
Cannot build Tools because _MSC_VER not match

### ISSUE THREAD

**Issue by FYKun** [RobotSDK/RobotSDK#1]
qtmain.lib(qtmain_win.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“17
00”不匹配值“1600”(main.obj 中)
......\Tools\ConfigSystem\ConfigSystem.exe : fatal error LNK1319: 检测到 1 个
不匹配项
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 11.
0\VC\BIN\amd64\link.EXE"”: 返回代码“0x527”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 11.
0\VC\BIN\amd64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “cd”: 返回代码“0x2”
Stop.

**Comment by alexanderhmw** [comment]
qtmain.lib(qtmain_win.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“17
00”不匹配值“1600”(main.obj 中)
请将c:\Build删除后重新安装

**Comment by alexanderhmw** [comment]
Build中的main.obj是VS2010编译的中间结果，一直残留在那，当升级到VS2012后，main.obj中的_MSC_VER标记仍然是老的。
解决方法，完全重新编译

**Comment by FYKun** [comment]
有可能是之前误操作，使用vs2010的控制台编译了一次，问题已经解决，感谢@alexanderhmw
