### ISSUE TITLE
URG采集程序问题

### ISSUE THREAD

**Issue by FYKun** [RobotSDK/RobotSDK#16]
总结就是因为SDK3的生产消费模型的限制，当时激光采集频率设置比较麻烦；与此同时返回的时间戳很不均匀。

实际上URG是触发式采集的，他会自己返回一个时间戳，数据之间间隔固定是n_25 ms ， 假如我们设置采集频率为m_25 ms 那么实际的采集频率会在 max(n,m)_25 ms 和 (max(n,m)+1)_25 ms 之间跳动，n,m都是正整数。假如我们设置的并不是25ms的倍数，那么由于需要等待硬件以25ms为周期返回数据，每次都会有延迟，所以最后的采集时间间隔是周期性变化的，并不稳定。

另外假如采集频率设置小于25ms，在运算量不大的情况下就能保证数据最后返回的一直是25ms间隔，但是会造成大量的信号堵塞。

**Comment by cretaceous-creature** [comment]
这个在第一代不就已经解决了么。。。。我记得。。。

2015-05-06 22:57 GMT+08:00 FYKun notifications@github.com:

**Comment by alexanderhmw** [comment]
这个问题一直没有解决，因为Qt的Timer在windows下不够准。SDK2.2和3的SensorTimer中的Timer和Node之间的通信是线程间通信，所以在超频的时候会出现信号冗余，sdk3通过强制断开链接清除了事件队列冗余，保证能够强制关闭节点。
解决方案是，通过while(flag)循环采集，flag一定要带volatile，否则停不下来。因为URG的采集是阻塞式，通过timeout跳出等待。SDK3的SensorTimer无法实现。使用SDK4，先建立URG的QObject采集类，然后让其在qobjetpool线程while采集，有数据，得到时间戳，然后发信号给Node。数据采集类和信号通信建立方式参照我的ROSInterface和Module里的传感器模块。

**Comment by alexanderhmw** [comment]
@FYKun URG也可以用QTimer进行驱动：

```
The accuracy of timers depends on the underlying operating system and hardware. Most platforms support a resolution of 1 millisecond, though the accuracy of the timer will not equal this resolution in many real-world situations.

The accuracy also depends on the timer type. For Qt::PreciseTimer, QTimer will try to keep the accurance at 1 millisecond. Precise timers will also never time out earlier than expected.

For Qt::CoarseTimer and Qt::VeryCoarseTimer types, QTimer may wake up earlier than expected, within the margins for those types: 5% of the interval for Qt::CoarseTimer and 500 ms for Qt::VeryCoarseTimer.
```

QTimer的默认类型是Qt::CoarseTimer。
如果没有问题，请及时关闭问题
