### ISSUE TITLE
amcl定位问题

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/RobotSDK#17]
何组长，我在使用ros的amcl定位，在rviz中选择PoseArray可视化，发现效果如下：
![screenshot from 2015-06-03 09_15_05](https://cloud.githubusercontent.com/assets/8281407/7951588/fa85903c-09db-11e5-82ab-6813668bedc3.png)
我现在的定位效果很差，用手柄遥控走的话，会发现定位结果不断的在跳。我是使用"/amcl_pose" topic 下的pose项作为当前的定位结果。

amcl的参数配置如下：
![qq 20150603104206](https://cloud.githubusercontent.com/assets/8281407/7951679/4fb8e602-09dd-11e5-98df-af26299a31c1.png)
![qq 20150603104230](https://cloud.githubusercontent.com/assets/8281407/7951682/55fb1f94-09dd-11e5-9313-b243d3b329c8.png)

现在我也不知道是哪里出了问题。。。

**Comment by alexanderhmw** [comment]
这是多少帧数据的可视化呀，particle怎么这么分散，可视化的时候调一下颜色，都是红色分辨不出来。
你把以下几个问题给我介绍一下：
1) AMCL需要odometry，你具体用的是什么来提供的（Encoder/IMU?），精度如何。
2) 和粒子滤波相关的参数有odom_alpha1~2 (odometry的旋转误差)和odom_alpha3~4 (odometry的平移误差)，你使用的是默认参数，需要调整。
3) 我用的是map->odom的tf得到定位数据，你可以把TF可视化到RVIZ
4) 把激光点投上来
5) 把TF链发上来

**Comment by mjlsuccess** [comment]
amcl的odometry用的是Encoder/IMU, 精度是走18米偏差10cm
下面是刚启动时的TF图，红色点是激光数据：
![screenshot from 2015-06-03 15 03 00](https://cloud.githubusercontent.com/assets/8281407/7954583/512db7a8-0a03-11e5-9bf8-0953eb8607a1.png)
走一小段直线后就成这样了：
![screenshot from 2015-06-03 15 00 13](https://cloud.githubusercontent.com/assets/8281407/7954591/695b1a46-0a03-11e5-9973-c102920ab336.png)
![screenshot from 2015-06-03 15 00 33](https://cloud.githubusercontent.com/assets/8281407/7954601/7f3867ec-0a03-11e5-9c6a-02205c9c1572.png)

TF 链如下：
![screenshot from 2015-06-03 15 17 03](https://cloud.githubusercontent.com/assets/8281407/7954617/9b52c18e-0a03-11e5-80af-653c6c50655c.png)
Odometry和TF都是用rosinterface里的接口写的，代码如下：

```
    odompub = new ROSPub<nav_msgs::Odometry>("/odom", 100, "odom_pub");
    odom2baselink = new ROSTFPub("base_link", "odom");
    baselink2laser = new ROSTFPub("laser", "base_link");


         //send the transform
         ///odom ---> base_link
         tf::Transform trans1;   
         tf::Quaternion quat = tf::createQuaternionFromYaw(vars->theta - M_PI/2.0);
         trans1.setRotation(quat);
         trans1.setOrigin(tf::Vector3(vars->x,vars->y,0.0));
         vars->odom2baselink->sendTF(trans1);

         ///base_link ---> laser
         tf::Transform trans2;
         trans2.setOrigin(tf::Vector3(-0.287,0.625 , 0));
         tf::Quaternion quat2 = tf::createQuaternionFromYaw(M_PI/2.0);
         trans2.setRotation(quat2);
         vars->baselink2laser->sendTF(trans2);

         //next, we'll publish the odometry message over ROS
         nav_msgs::Odometry odom;
         odom.header.stamp = vars->current_time;
         odom.header.frame_id = "odom";
         //set the position
         odom.pose.pose.position.x = vars->x;
         odom.pose.pose.position.y = vars->y;
         odom.pose.pose.position.z = 0.0;
         geometry_msgs::Quaternion odom_quat = tf::createQuaternionMsgFromYaw(vars->theta - M_PI/2.0);
         odom.pose.pose.orientation = odom_quat;
         //set the velocity
         odom.child_frame_id = "base_link";
         odom.twist.twist.linear.x = vars->vx;
         odom.twist.twist.linear.y = vars->vy;
         odom.twist.twist.angular.z = vars->vtheta;

         //publish the message
         vars->odompub->sendMessage(odom);
```

**Comment by alexanderhmw** [comment]
首先先解决AMCL正确使用这个问题，看下面两个图：（同时你可以看一下我发的视频，对比一下）
![image](https://cloud.githubusercontent.com/assets/5616828/7955266/e97b1b46-0a11-11e5-8049-814366bb5b13.png)
![image](https://cloud.githubusercontent.com/assets/5616828/7955270/f0b932e4-0a11-11e5-8e3f-b47e818ca198.png)

发现map坐标系移动了，而odom坐标系没有移动。
正常的结果是map坐标系不动，因为它始终位于OGM的坐标原点，定义map的坐标系。而odom的坐标系是移动的，因为AMCL得到的结果是map->odom的TF，即对odometry定位的修正。
明白了这一点，就知道如何正确使用AMCL了。

总结一下：
你需要提供给AMCL的东西：
1) 激光数据 (sensor_msgs/LaserScan), Topic默认是scan, frame默认是laser
2) Odometry定位结果 (tf::StampedTransform, odom -> base_link), 你的odom2baselink, 但是缺少时间戳，这是很重要的。odompub不是AMCL需要的，当然是可以发布，但和AMCL无关。
3) Laser的标定结果 (tf::StampedTransform, base_link -> laser)， 这个可以用你的baselink2laser，但最好用static_tf:

```
rosrun tf static_transform_publisher x y z roll pitch yaw base_link laser 10
```

4) OGM（nav_msgs/OccupancyGrid），这个通过map_server发布。
你需要设定的参数：
odom_alpha_1~4，你的odometry误差大，所以应相对提高particle filter的误差散布。在RVIZ中可以查看particle filter来验证设定的参数。

**Comment by mjlsuccess** [comment]
问题已经解决了：在RVIZ中的fixframe选择map就能解决map坐标系移动而odom坐标系不移动的问题；参数odom_alpha_1~4（默认0.2），调小可以解决PoseArray散乱的问题

**Comment by alexanderhmw** [comment]
（1）强烈建议使用tf::StampedTransform。时间戳对于ROS非常重要。
（2）odom_alpha值小意味着更依靠odometry定位，大意味着更依靠匹配修正。在走道室内良好环境和低精度odometry下，应该使用更大的odom_alpha以得到良好的定位结果。例如，这次挑战参赛，机器人使用了高精度陀螺仪，所以alpha1~2非常小，只有0.01。而使用的编码器精度非常低，而且路面不平整，所以alpha3~4非常大，达到2.5。所以，不是简单调小alpha，粒子不散乱就解决问题了，而是要达到alpha1~4与odometry误差模型相匹配，从而得到稳定定位结果。

**Comment by TiderFang** [comment]
看到你们关于odom的讨论，对于odom这个坐标系很困惑。因此搜了一下资料，发现odom是一个固定的坐标系，所以odom坐标系移动应该是不正确的。
[Rep 105](http://www.ros.org/reps/rep-0105.html#abstract)提到了这个：
The coordinate frame called odom is a world-fixed frame。
The coordinate frame called map is a world fixed frame。
