### ISSUE TITLE
加入插件qwt后高程程序编译失败

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/RobotSDK#19]
何组长，我想在程序中使用qwt插件，新建的非robotSDK程序运行没有问题，但加入到RobotSDK的高层程序后编译就报错。结果如下：
![screenshot from 2015-06-18 09 00 44](https://cloud.githubusercontent.com/assets/8281407/8222020/8c9adae6-1598-11e5-9afd-b43a5e2393b8.png)
下面的是非robotSDK程序编译的结果：
![screenshot from 2015-06-18 09 02 08](https://cloud.githubusercontent.com/assets/8281407/8222132/cafd7aae-1599-11e5-8457-77177ae35796.png)

可以看到，这两个程序链接qt函数库的位置不一样：
-L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
-L/opt/Qt5.4.1/5.4/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
但是我在 /usr目录下并没有发现有X11R6的文件夹。。

**Comment by alexanderhmw** [comment]
这个在之前某一个版的RobotSDK_4.0突然出现过，无法正确解析到Qt5GUI等Qt5的动态链接库。
最新版本的RobotSDK_4.0把Qt相关的预制环境变量全部去掉，使用Ubuntu的qt5-default (5.2)就没有问题了。具体为什么，我也不知道。从最新的Qt5.4突然出现该问题的。

解决方法：
（1）手动链接LIB，直接在.pro工程文件中加入LIBS += -L(Qt库路径) -l(QtGui或者其他Qt的库，出错信息里列的)，对于最新的Qt5.4有效，但是很麻烦，你可写一个.pri文件，每次include它就可以了。
（2） 不使用最新的Qt5.4，我感觉它有Bug。使用qt5-default

**Comment by mjlsuccess** [comment]
第一种方法比较简单，直接在.pro文件中加上下面这句话就好了。
LIBS += -L/opt/Qt5.4.1/5.4/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread
