### ISSUE TITLE
RobotSDK3.0与新版本Qt的问题

### ISSUE THREAD

**Issue by 05F3759DF** [RobotSDK/RobotSDK#20]
环境win8.1 x64，VS2013，安装RobotSDK 3.0，使用Qt 5.5.0和5.4.x，在安装时都出现ConfigSystem应用程序并行配置不正确的问题（如图）。后改用Qt 5.3.x，正常。

过程中尝试使用qmake出的vs工程直接编译运行没有出错，所以可能是生成的makefile的问题？

另外一个小问题：Install.bat, Line55,
应该为cd "%TMPDISKDRIVER%:\Build\RobotSDK\Tools\ConfigSystem"
原文件中少进了一级目录，会出现ConfigSystem找不到的问题。

![sdktool](https://cloud.githubusercontent.com/assets/7190818/8778605/6f512028-2f31-11e5-83ca-aae4dff5a716.jpg)

**Comment by alexanderhmw** [comment]
自从Qt5.4后，类似的bug就出现了。Qt有一个mkspecs的文件夹，用于管理各种环境下基于Qt的程序编译配置。从Qt5.4之后，Qt的编译配置可能发生了变化，使用qmake时，无法“正确配置”Qt环境（需要用户额外配置Qt自身的库环境，如QtCore, QtWidget等），这在4.0也出现了该问题。目前我还不知道如何完美解决，所以推荐用之前的Qt版本，我现在用的是5.2。
关于，Install.bat，如果确实是这样，你可以修改Install.bat并commit&push到GitHub。

**Comment by alexanderhmw** [comment]
如果问题已解决，请发起者关闭issue话题。
