### ISSUE TITLE
一个Simulator模块，调试时generateSourceData函数已经return 1但是监视中还是红线下降沿

### ISSUE THREAD

**Issue by FYKun** [RobotSDK/RobotSDK#3]
自然后续的模块也没有接受到输入

**Comment by alexanderhmw** [comment]
把generateSourceData函数发上来

**Comment by FYKun** [comment]
```
if(vars->inFile.eof())
{ 
    return 0;//这儿从来没有触发过
}
short * dataBuffer;
dataBuffer = new short [outputdata->dataSize];
vars->inFile.read((char *)&outputdata->timestamp,sizeof(int));
vars->inFile.read((char *)dataBuffer,outputdata->dataSize*sizeof(short));
for(int i = 0 ; i < outputdata->dataSize ; ++i)
{
    outputdata->data[i] = (double)dataBuffer[i] / params->unit;
}
delete [] dataBuffer;
return 1;//这儿的断点每次都触发
```

**Comment by alexanderhmw** [comment]
是完全没有蓝色下降沿？

**Comment by FYKun** [comment]
对，这里是监视输出

Open node Simulator_Sensor_URG_URG successfully.
Close node Simulator_Sensor_URG_URG successfully.
Open node Simulator_Sensor_URG_URG successfully.
2015-04-03 13:35:47:961 : node Simulator_Sensor_URG_URG triggered.
2015-04-03 13:35:50:132 : node Simulator_Sensor_URG_URG ended unsuccessfully.

**Comment by FYKun** [comment]
另外set时间也没有用，刚才的触发都是每次按按钮发送startSimuSignal信号才触发的

**Comment by alexanderhmw** [comment]
只有URG的simulator出现这个情况，还是所有Simulator都出现了这个问题

**Comment by FYKun** [comment]
是这个新写的程序有问题...老程序可以正常模拟，应该是有写错的地方，不过没找到...

**Comment by alexanderhmw** [comment]
把高层程序相关代码也发过来

**Comment by FYKun** [comment]
#include "sampleapp.h"

#pragma comment(lib,"Kernel.lib")

SampleApp::SampleApp(QWidget *parent)
    : QMainWindow(parent)
{
    ui.setupUi(this);

```
ui.starttime->setText("0");
ui.simurate->setText("1");
```

//=========================================================
//Create Nodes:
    Simulator \* URG = new Simulator("SampleLib","Sensor_URG","URG","config.xml",QTime(),1);
    URG->setOutputNodesName(QStringList()<<"URG_Visualization");

```
VisualizationMono * URG_Visualization = new VisualizationMono("SampleLib","Sensor_URG","URG_Visualization","config.xml");
URG_Visualization->setInputNodesName(QStringList()<<"URG");
URG_Visualization->connectExternalTrigger(0,DRAINSLOT);
```

//=========================================================
//Config Edge:
    bool isMonitor = 1;//false;
    edge.addNode(URG,1,isMonitor);
    edge.addNode(URG_Visualization,0,0);
    edge.connectAll();

//=========================================================
//Config UI:
    bool flag = 1;
    flag&=bool(connect(ui.open,SIGNAL(clicked()),&edge,SLOT(openAllNodesSlot())));
    flag&=bool(connect(ui.close,SIGNAL(clicked()),&edge,SLOT(closeAllNodesSlot())));

```
flag&=bool(connect(ui.setrate,SIGNAL(clicked()),this,SLOT( setSimuRateSlot())));
flag&=bool(connect(this,SIGNAL( setSimuSimuRateSignal(double) ),URG,SLOT(setSimulateRateSlot(double))));

flag&=bool(connect(ui.settime,SIGNAL(clicked()),this,SLOT( setSimuSlot())));
flag&=bool(connect(this,SIGNAL( setSimuStartTimeSignal(QTime) ),URG,SLOT(setStartTimeSlot(QTime))));

flag&=bool(connect(ui.sync,SIGNAL(clicked()),this,SLOT( syncSimuSlot())));
flag&=bool(connect(this,SIGNAL( syncSimuSignal() ),URG,SLOT(syncTimeTrackSlot())));

flag&=bool(connect(ui.start,SIGNAL(clicked()),this,SLOT( startSimuSlot())));
flag&=bool(connect(this,SIGNAL( startSimuSignal() ),URG,SLOT(startSimulatorSlot())));

flag&=bool(connect(ui.stop,SIGNAL(clicked()),this,SLOT( stopSimuSlot())));
flag&=bool(connect(this,SIGNAL( stopSimuSignal() ),URG,SLOT(stopSimulatorSlot())));

flag&=bool(connect(ui.reset,SIGNAL(clicked()),this,SLOT( resetSimuSlot())));
flag&=bool(connect(this,SIGNAL( resetSimuSignal() ),URG,SLOT(resetTimeTrackSlot())));

ui.tabWidget->addTab(&edge,"monitor");

QList<QWidget *> widgets;
widgets= URG_Visualization->getVisualizationWidgets();
ui.scrollArea1->setWidget(widgets[0]);
```

}

SampleApp::~SampleApp()
{
    edge.clear();
}

void SampleApp::syncSimuSlot()
{
    emit syncSimuSignal();
}

void SampleApp::startSimuSlot()
{
    emit startSimuSignal();
}

void SampleApp::stopSimuSlot()
{
    emit stopSimuSignal();
}

void SampleApp::resetSimuSlot()
{
    emit resetSimuSignal();
}

void SampleApp::setSimuSlot()
{
    emit setSimuStartTimeSignal(QTime::fromMSecsSinceStartOfDay(ui.starttime->text().toInt()));
    //  emit setSimuSimuRateSignal(ui.simurate->text().toDouble());
}

void SampleApp::setSimuRateSlot()
{
    emit setSimuSimuRateSignal(ui.simurate->text().toDouble());
}

**Comment by alexanderhmw** [comment]
有一个问题，你的Simulator没有连接IntrinsicTrigger，但不知道还有没有其它问题

**Comment by FYKun** [comment]
之前写的都没有internelTrigger啊

**Comment by alexanderhmw** [comment]
我想错了，已经删了

**Comment by alexanderhmw** [comment]
话说你的断点在return 1之前有没有设置

**Comment by alexanderhmw** [comment]
就是说数据拷贝都执行了

**Comment by alexanderhmw** [comment]
我知道了，你又没有给timeStamp赋值

**Comment by alexanderhmw** [comment]
simulator需要给timeStamp赋值

**Comment by alexanderhmw** [comment]
否则即使返回值为1，Kernel也会发送错误，因为模拟器需要时间戳来进行模拟

**Comment by FYKun** [comment]
soga!!!
