### ISSUE TITLE
qtcreator不能删除文件

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/RobotSDK#4]
何组长，在qtcreator中删除文件失败，见图片
![screenshot from 2015-04-07 22 40 10](https://cloud.githubusercontent.com/assets/8281407/7025597/31af3414-dd77-11e4-9ad6-f0da15c31ee4.png)
![screenshot from 2015-04-07 22 40 36](https://cloud.githubusercontent.com/assets/8281407/7025598/31af5e30-dd77-11e4-89aa-4429e33929b7.png)

**Comment by alexanderhmw** [comment]
你直接删.pri里面对应的文件名就可以了（根本方法），可以不通过IDE删除。

**Comment by mjlsuccess** [comment]
嗯，问题解决了

**Comment by alexanderhmw** [comment]
解决后，请关闭Issue
