### ISSUE TITLE
qtcreator添加文件后，编译报错

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/RobotSDK#5]
何组长，我在qtcreator中通过UI加入文件后编译报错，过程如下：
![screenshot from 2015-04-08 23 04 46](https://cloud.githubusercontent.com/assets/8281407/7048160/c9cad0d8-de43-11e4-9f75-83da43ab79aa.png)
![screenshot from 2015-04-08 23 05 04](https://cloud.githubusercontent.com/assets/8281407/7048161/c9cfe21c-de43-11e4-9893-17728ecff920.png)
![screenshot from 2015-04-08 23 05 28](https://cloud.githubusercontent.com/assets/8281407/7048162/c9d2745a-de43-11e4-9dd8-5ba5848a534b.png)

**Comment by alexanderhmw** [comment]
不能用$$PWD，要用相对于.pro或者.pri的相对路径，用个全文替换就可以了

**Comment by mjlsuccess** [comment]
把.pri文件清空，重新添加所有文件，这时候.pri文件会有$$PWD, 用全文替换成相对路径，然后clean ，rebuild。
