### ISSUE TITLE
BugReport

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/RobotSDK#7]
新建Qt Application后，在第三步修改了主类名（Mainwindow->Test），然后configProject，导致构建错误（见图，ui找不到组件）。特别：1. 经测试不改主类名的情况下不会有问题；2.在config之前在ui上添加的组件也不会出错（图中的button是之前添加的，未报错，button2是后添加的，报错）

![builderror](https://cloud.githubusercontent.com/assets/8281407/7087212/68b7de02-dfbb-11e4-90ab-66357fdb9dc6.png)

**Comment by alexanderhmw** [comment]
你把.pro的内容贴上来

**Comment by mjlsuccess** [comment]
#-------------------------------------------------
#

# Project created by QtCreator 2015-04-11T10:08:04

#
#-------------------------------------------------

SOURCES += main.cpp\
        test.cpp

HEADERS  += test.h

FORMS    += test.ui

PROJNAME = Test2
INSTTYPE = APP
include(RobotSDK_Main.pri)

**Comment by alexanderhmw** [comment]
把test.h贴上来，还有 $(HOME)/Build/APP/Test2/UI 下的ui_test.h

**Comment by 05F3759DF** [comment]
I am Xu Liangwei. I found that there isn't '#include <RobotSDK_Global.h>' in test.h which can be   automatically added in default 'MainWindow' object. I tried adding it, but nothing changed. The followings are the files you need.

#ifndef TEST_H
#define TEST_H

#include <QMainWindow>

namespace Ui {
class Test;
}

class Test : public QMainWindow
{
    Q_OBJECT

public:
    explicit Test(QWidget *parent = 0);
    ~Test();

private:
    Ui::Test *ui;
};

#endif // TEST_H

/********************************************************************************
*\* Form generated from reading UI file 'test.ui'
**
*\* Created by: Qt User Interface Compiler version 5.4.1
**
*\* WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TEST_H
#define UI_TEST_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Test
{
public:
    QWidget *centralWidget;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

```
void setupUi(QMainWindow *Test)
{
    if (Test->objectName().isEmpty())
        Test->setObjectName(QStringLiteral("Test"));
    Test->resize(400, 300);
    centralWidget = new QWidget(Test);
    centralWidget->setObjectName(QStringLiteral("centralWidget"));
    pushButton = new QPushButton(centralWidget);
    pushButton->setObjectName(QStringLiteral("pushButton"));
    pushButton->setGeometry(QRect(120, 70, 99, 27));
    pushButton_2 = new QPushButton(centralWidget);
    pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
    pushButton_2->setGeometry(QRect(130, 120, 99, 27));
    Test->setCentralWidget(centralWidget);
    menuBar = new QMenuBar(Test);
    menuBar->setObjectName(QStringLiteral("menuBar"));
    menuBar->setGeometry(QRect(0, 0, 400, 25));
    Test->setMenuBar(menuBar);
    mainToolBar = new QToolBar(Test);
    mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
    Test->addToolBar(Qt::TopToolBarArea, mainToolBar);
    statusBar = new QStatusBar(Test);
    statusBar->setObjectName(QStringLiteral("statusBar"));
    Test->setStatusBar(statusBar);

    retranslateUi(Test);

    QMetaObject::connectSlotsByName(Test);
} // setupUi

void retranslateUi(QMainWindow *Test)
{
    Test->setWindowTitle(QApplication::translate("Test", "Test", 0));
    pushButton->setText(QApplication::translate("Test", "PushButton", 0));
    pushButton_2->setText(QApplication::translate("Test", "PushButton", 0));
} // retranslateUi
```

};

namespace Ui {
    class Test: public Ui_Test {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TEST_H

**Comment by dog2cat** [comment]
I don't know why it was not pasted complete. The followings are the 'include's

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

**Comment by 05F3759DF** [comment]
I don't know it was pasted incompletely. The picture shows the 'include's.
![screenshot from 2015-04-11 11 29 00](https://cloud.githubusercontent.com/assets/7190818/7100075/203835b8-e03e-11e4-8d10-fa0de5ab49f7.png)
![screenshot from 2015-04-11 11 30 54](https://cloud.githubusercontent.com/assets/7190818/7100077/3ec0a7c2-e03e-11e4-8255-8269666d3d53.png)

**Comment by alexanderhmw** [comment]
目前看上去没有问题，你先qmake一下，再rebuild，报告以下编译输出（不是错误列表）

**Comment by 05F3759DF** [comment]
I tried and failed.

**Comment by alexanderhmw** [comment]
把编译输出给我看一下

**Comment by 05F3759DF** [comment]
11:36:55: Running steps for project Test2...
11:36:55: Starting: "/usr/bin/make" clean
rm -f ../Build/APP/Test2/MOC/moc_test.cpp
rm -f ../Build/APP/Test2/UI/ui_test.h
rm -f ../Build/APP/Test2/OBJ/Debug/main.o ../Build/APP/Test2/OBJ/Debug/test.o ../Build/APP/Test2/OBJ/Debug/moc_test.o
rm -f _~ core *.core
11:36:55: The process "/usr/bin/make" exited normally.
11:36:55: Configuration unchanged, skipping qmake step.
11:36:55: Starting: "/usr/bin/make" 
/home/xlw/Qt5.4.1/5.4/gcc_64/bin/uic ../Test2/test.ui -o ../Build/APP/Test2/UI/ui_test.h
g++ -c -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I../Test2 -I. -I../Test2 -I../SDK/RobotSDK/Kernel/include -I../SDK/RobotSDK/Module/include -I../Qt5.4.1/5.4/gcc_64/include -I../Qt5.4.1/5.4/gcc_64/include/QtOpenGL -I../Qt5.4.1/5.4/gcc_64/include/QtWidgets -I../Qt5.4.1/5.4/gcc_64/include/QtGui -I../Qt5.4.1/5.4/gcc_64/include/QtXml -I../Qt5.4.1/5.4/gcc_64/include/QtCore -I../Build/APP/Test2/MOC -I../Build/APP/Test2/UI -I../Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++ -o ../Build/APP/Test2/OBJ/Debug/main.o ../Test2/main.cpp
g++ -c -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I../Test2 -I. -I../Test2 -I../SDK/RobotSDK/Kernel/include -I../SDK/RobotSDK/Module/include -I../Qt5.4.1/5.4/gcc_64/include -I../Qt5.4.1/5.4/gcc_64/include/QtOpenGL -I../Qt5.4.1/5.4/gcc_64/include/QtWidgets -I../Qt5.4.1/5.4/gcc_64/include/QtGui -I../Qt5.4.1/5.4/gcc_64/include/QtXml -I../Qt5.4.1/5.4/gcc_64/include/QtCore -I../Build/APP/Test2/MOC -I../Build/APP/Test2/UI -I../Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++ -o ../Build/APP/Test2/OBJ/Debug/test.o ../Test2/test.cpp
../Test2/test.cpp: In constructor 'Test::Test(QWidget_)':
../Test2/test.cpp:8:19: warning: statement has no effect [-Wunused-value]
     ui->pushButton;
                   ^
../Test2/test.cpp:9:9: error: 'class Ui::Test' has no member named 'pushButton_2'
     ui->pushButton_2;
         ^
make: **\* [../Build/APP/Test2/OBJ/Debug/test.o] Error 1
11:36:56: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project Test2 (kit: Desktop Qt 5.4.1 GCC 64bit)
When executing step "Make"
11:36:56: Elapsed time: 00:02.

**Comment by alexanderhmw** [comment]
奇怪，Ui::Test 里面有变量pushButton_2呀，把工程打包发过来，我看一下

**Comment by alexanderhmw** [comment]
另外，把工程路径下的Makefile贴上来，有可能ui_test.h没有被正确包含

**Comment by 05F3759DF** [comment]
I removed the folder "build-Test2-Desktop_Qt_5_4_1_GCC_64bit-Debug" manually and rebuild the project successfully('clean' in qt doesn't work). Maybe a command to remove the files of old version while configuring the project  is needed. I send the file to your 163 email address.

**Comment by alexanderhmw** [comment]
clean只是针对于编译过程（make和make install），Qt程序编译还需要在这之前进行qmake的moc和uic。所以之前让你先qmake一下再重新编译，就是需要重新生成moc和ui。以后遇到这种问题，是不许要删除编译过程的。
问题解决后请总结并关闭评论。

**Comment by 05F3759DF** [comment]
总结
问题简述：在使用SDKtool设置Qt工程后，编译提示ui找不到组件。
解决方案：先尝试执行qmake，再重新编译，若无效则手动删除"build-***-Desktop_Qt_5_X_X_GCC_64bit-Debug"文件夹，使得Qt重新生成编译文件。
