### ISSUE TITLE
RobotSDK 4.0 测试版发布

### ISSUE THREAD

**Issue by alexanderhmw** [RobotSDK/RobotSDK#8]
大家好，

RobotSDK 4.0 已经完成在Linux和Windows下的测试。
目前代码包含Kernel和Sample，可以让大家对4.0有一个直观感觉。

Clone代码的时候，请加入 “-b RobotSDK_4.0” 参数
或者进入GitHub，点击左上角的branch，切换到 RobotSDK_4.0，然后右侧下载压缩包

安装与3.0类似，直接运行install.sh(bat), Kernel会被安装到：
Linux: $(HOME)/SDK/RobotSDK_4.0
Windows: c:/SDK/RobotSDK_4.0

Sample中有两个工程，TestModule（模块开发），TestGraph（高层程序）
先编译两个样例，推荐用QtCreator。然后运行TestGraph，出现文件打开窗口，打开编译好的动态链接库TestModule.so (dll)，就可以看到Sample了。（没有系统环境变量要求）

Sample很简单，一个Node随机生成数字，然后奇数从0号端口输出，偶数从1号端口输出。
然后就有两个Node从0号端口接受数据显示。

关键是希望大家看一眼源代码，通过C++11提供的相关技术，现在的代码变得自由简洁，基本原理和3.0是一致的。
模块开发：向C一样自由，没有冗长的预置代码（无须开发工具辅助）。样例中包含两个Class的模块：RandomGenerator和NumberViewer。
高层程序：你会发现可以用脚本控制（因为Node不再分Type），在正式版将有一个解释器（Robot-X），有了这个解释器，你不用在写高层程序，只用画图。

Windows用户只能使用VS2013进行编译，因为VS2013对C++11的支持较为全面（比GCC还差得远）。可参考 https://msdn.microsoft.com/en-us/library/hh567368.aspx

期待大家前来试用！

**Comment by alexanderhmw** [comment]
Preview: Robot-X自动生成可视化图模型（Sample）
![image](https://cloud.githubusercontent.com/assets/5616828/7112478/e763ee44-e204-11e4-8615-4b4865ffe12f.png)

**Comment by alexanderhmw** [comment]
Preview: Robot-X UI (Sample)
1、建立三个节点
![image](https://cloud.githubusercontent.com/assets/5616828/7129158/5da7af22-e297-11e4-99f0-e1b48695002b.png)
2、手动（Drag n Drop）链接端口
![image](https://cloud.githubusercontent.com/assets/5616828/7129178/acd9f3fc-e297-11e4-94d3-9de5d7ca90c4.png)
3、启动并显示各个节点UI
![image](https://cloud.githubusercontent.com/assets/5616828/7129203/f9fd0548-e297-11e4-865e-ca7f13f8e29e.png)
4、输出图模型文件
![out](https://cloud.githubusercontent.com/assets/5616828/7129210/0c0f6956-e298-11e4-8b0b-cb0ecead4eb7.png)

**Comment by alexanderhmw** [comment]
Preview: Robot-X 节点操作
![image](https://cloud.githubusercontent.com/assets/5616828/7129236/618bdc20-e298-11e4-8124-021f8f5fc0d4.png)

1、支持热插拔：随时更换节点的扩展名（ExName）、动态分享库（Shared Library）和 配置文件（Config File），而无需重载整个程序或者全部节点。（注意：Qt的动态分享库载入后不会释放，所以在载入后出现库文件修改，修改部分不会载入，需要重启Robot-X）
2、可以随意控制节点开关，显示节点对应的Widget：相对于3.0，优化了关闭状态，保证数据不阻塞。
3、支持虚拟节点（只有节点名称，没有实质动态分享库）：虚拟节点可以参与图模型构建，无法控制节点（因为目前没有实质节点）。当图模型确定后，可以使用Generate Code生成模块开发所需的.h和.cpp。模块开发完成并编译到动态分享库后，可以使用Change Library实现热插入。意义在于真正实现了Top-Down的开发模式。
4、Drag n Drop 链接节点间端口：通过手动拖拽释放，实现节点间链接，建立通信通路。

**Comment by alexanderhmw** [comment]
@FYKun  关于关闭机制：
3.0的关闭机制是完全断绝信号通路，等待退出现有线程。会出现 生产--消费 不平衡。
4.0的关闭机制是使用EventFilter，数据仍然接受（消费），但是都被过滤掉了，并且无需等待线程退出（因为线程将一直存在，直到节点消亡）。这样保证 生产--消费 平衡，保证系统稳定性。

另外，关于Robot-X的角色：
Robot-X是一个超级高层程序，有了他就不需要开发新的高层程序（不是不可以）。
X可以自由载入任何RobotSDK_4.0开发的模块作为节点，并实现节点间互联（人工或者脚本）。
X可以实现自顶向下的系统开发模式，因为可以使用虚拟节点构建高层图模型，然后生成对应的模块开发代码。

**Comment by FYKun** [comment]
就是说现在关闭后那些被堵塞的信号会被过滤掉不处理？

**Comment by alexanderhmw** [comment]
是的，阻塞的信号会被过滤掉，不处理。一旦Open，数据就会进入模块处理。这样保证数据流一直畅通

**Comment by alexanderhmw** [comment]
Preview: 简化后的Robot-X：
![image](https://cloud.githubusercontent.com/assets/5616828/7130928/3ed76db4-e2b3-11e4-92d0-d45c4709c413.png)

**Comment by alexanderhmw** [comment]
Preview: Robot-X 基于虚拟节点的高层图模型创建
![image](https://cloud.githubusercontent.com/assets/5616828/7135531/9c345d4e-e2e2-11e4-911e-007527c876c1.png)

**Comment by alexanderhmw** [comment]
Preview: Robot-X 优化图模型构建
![image](https://cloud.githubusercontent.com/assets/5616828/7136097/147b0aaa-e2e8-11e4-9cfa-48036655ac49.png)

**Comment by alexanderhmw** [comment]
Preview: Robot-X 保存图模型到脚本 & 通过脚本建立图模型

```
N,A::0, ,Config.xml,0,2
N,B::1, ,Config.xml,3,4
N,C::2, ,Config.xml,2,3
N,D::4, ,Config.xml,5,0
N,NumberViewer::even,/home/alexanderhmw/Git/dev/RobotSDK/Src/Sample/build-TestModule-Desktop_Qt_5_4_1_GCC_64bit-Release/libTestModule.so,Config.xml,1,0
N,NumberViewer::odd,/home/alexanderhmw/Git/dev/RobotSDK/Src/Sample/build-TestModule-Desktop_Qt_5_4_1_GCC_64bit-Release/libTestModule.so,Config.xml,1,0
N,RandomGenerator::random,/home/alexanderhmw/Git/dev/RobotSDK/Src/Sample/build-TestModule-Desktop_Qt_5_4_1_GCC_64bit-Release/libTestModule.so,Config.xml,0,2
E,A::0,1,B::1,1
E,A::0,0,B::1,0
E,B::1,1,C::2,1
E,B::1,0,C::2,0
E,B::1,3,D::4,4
E,B::1,2,D::4,3
E,C::2,0,D::4,0
E,C::2,1,D::4,1
E,C::2,2,D::4,2
E,RandomGenerator::random,0,B::1,2
E,RandomGenerator::random,1,NumberViewer::even,0
E,RandomGenerator::random,0,NumberViewer::odd,0
```

![image](https://cloud.githubusercontent.com/assets/5616828/7136849/9820a6ce-e2ef-11e4-9cdf-94356811ee36.png)

**Comment by alexanderhmw** [comment]
Preview: RobotSDK 自动生成模块开发代码
1、高层图模型设计
![image](https://cloud.githubusercontent.com/assets/5616828/7140453/40dd75ce-e306-11e4-99c9-d116f77dc86e.png)

2、生成非扩展节点代码（以SensorCamera为例）：
RobotSDK_4.0的模块开发只需要生成的两个文件（一个.h，一个.cpp），当然用户可以根据需要加入更多文件。

SensorCamera.h

```
#ifndef SENSORCAMERA
#define SENSORCAMERA

//=================================================
//Please add headers here:

//=================================================
//Port configuration

#undef NODE_CLASS
#define NODE_CLASS SensorCamera

#undef INPUT_PORT_NUM
#define INPUT_PORT_NUM 0

#undef OUTPUT_PORT_NUM
#define OUTPUT_PORT_NUM 1

//=================================================
//Params types configuration

//If you need refer params type of other node class, please uncomment below and comment its own params type.
//NODE_PARAMS_TYPE_REF(RefNodeClassName)
class NODE_PARAMS_TYPE : public NODE_PARAMS_BASE_TYPE
{

};

//=================================================
//Vars types configuration

//If you need refer vars type of other node class, please uncomment below and comment its own vars type.
//NODE_VARS_TYPE_REF(RefNodeClassName)
class NODE_VARS_TYPE : public NODE_VARS_BASE_TYPE
{

};

//=================================================
//Data types configuration

//If you need refer data type of other node class, please uncomment below and comment its own data type.
//NODE_DATA_TYPE_REF(RefNodeClassName)
class NODE_DATA_TYPE : public NODE_DATA_BASE_TYPE
{

};

//=================================================
//You can declare functions here

//=================================================

#endif
```

SensorCamera.cpp

```
#include"SensorCamera.h"

//If you need use extended node, please uncomment below and comment the using of default node
//USE_EXTENDED_NODE(ExtendedNodeClass[,...])
USE_DEFAULT_NODE

//=================================================
//Original node functions

//If you don't need initialize node, you can delete this code segment
NODE_FUNC_DEF_EXPORT(bool, initializeNode)
{
    return 1;
}

//If you don't need manually open node, you can delete this code segment
NODE_FUNC_DEF_EXPORT(bool, openNode)
{
    return 1;
}

//If you don't need manually close node, you can delete this code segment
NODE_FUNC_DEF_EXPORT(bool, closeNode)
{
    return 1;
}

//This is original main function, you must keep it
NODE_FUNC_DEF_EXPORT(bool, main)
{
    return 1;
}
```

3、生成扩展节点代码（以KeyPointsDetector::detector::SIFT为例）：

KeyPointsDetector.h

```
#ifndef KEYPOINTSDETECTOR
#define KEYPOINTSDETECTOR

//=================================================
//Please add headers here:

//=================================================
//Port configuration

#undef NODE_CLASS
#define NODE_CLASS KeyPointsDetector

#undef INPUT_PORT_NUM
#define INPUT_PORT_NUM 1

#undef OUTPUT_PORT_NUM
#define OUTPUT_PORT_NUM 1

//Uncomment below PORT_DECL and set input node class name
//PORT_DECL(%1, InputNodeClassName)

//=================================================
//Params types configuration

//If you need refer params type of other node class, please uncomment below and comment its own params type.
//NODE_PARAMS_TYPE_REF(RefNodeClassName)
class NODE_PARAMS_TYPE : public NODE_PARAMS_BASE_TYPE
{

};

//=================================================
//Vars types configuration

//If you need refer vars type of other node class, please uncomment below and comment its own vars type.
//NODE_VARS_TYPE_REF(RefNodeClassName)
class NODE_VARS_TYPE : public NODE_VARS_BASE_TYPE
{

};

//=================================================
//Data types configuration

//If you need refer data type of other node class, please uncomment below and comment its own data type.
//NODE_DATA_TYPE_REF(RefNodeClassName)
class NODE_DATA_TYPE : public NODE_DATA_BASE_TYPE
{

};

//=================================================
//You can declare functions here

//=================================================

#endif
```

KeyPointsDetector.cpp

```
#include"KeyPointsDetector.h"

//If you need use extended node, please uncomment below and comment the using of default node
//USE_EXTENDED_NODE(ExtendedNodeClass[,...])
USE_DEFAULT_NODE

//=================================================
//Original node functions

//If you don't need initialize node, you can delete this code segment
NODE_FUNC_DEF_EXPORT(bool, initializeNode)
{
    return 1;
}

//If you don't need manually open node, you can delete this code segment
NODE_FUNC_DEF_EXPORT(bool, openNode)
{
    return 1;
}

//If you don't need manually close node, you can delete this code segment
NODE_FUNC_DEF_EXPORT(bool, closeNode)
{
    return 1;
}

//This is original main function, you must keep it
NODE_FUNC_DEF_EXPORT(bool, main)
{
    return 1;
}

//=================================================
//Extended node functions

//If you don't need initialize node, you can delete this code segment
NODE_EXFUNC_DEF_EXPORT(bool, SIFT, initializeNode)
{
    return 1;
}

//If you don't need manually open node, you can delete this code segment
NODE_EXFUNC_DEF_EXPORT(bool, SIFT, openNode)
{
    return 1;
}

//If you don't need manually close node, you can delete this code segment
NODE_EXFUNC_DEF_EXPORT(bool, SIFT, closeNode)
{
    return 1;
}

//As an extended main function, if you delete this code segment, original main function will be used
NODE_EXFUNC_DEF_EXPORT(bool, SIFT, main)
{
    return 1;
}
```

对比Sample，你会发现 RobotSDK_4.0的模块开发非常简洁。

**Comment by alexanderhmw** [comment]
大家好，Robot-X已经开发完毕，同时也意味着RobotSDK_4.0正式进入alpha测试版。
期待大家前来测试。

@FYKun ,我觉得你可以开始用RobotSDK_4.0重写数据采集模块了。我会于这周内发布一个快速入门手册。
