### ISSUE TITLE
storage节点存数据问题

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/RobotSDK#9]
何组长，在存数据时出了问题, 我先后测试了两种不同的方法，但结果都是一样的
方法1:
 int i, n=draindata.size();
 for(i=0; i<n; i++)
    {
        SourceDrainMono_Sensor_stm32comm_Data *data = draindata[i];
        int time = ((data->timestamp.hour()_60 + data->timestamp.minute())_60  + data->timestamp.second()) _1000
                +data->timestamp.msec();
        vars->storagefile<<time<<'\t'<<data->x<<'\t'<<data->y<<'\t'<<data->theta<<'\t'
                        <<data->yaw<<'\t'<<data->leftodom<<'\t'<<data->rightodom<<'\t'<<std::endl;
    }
方法二：
for(i=n-1; i>=0; i--)
    {
        SourceDrainMono_Sensor_stm32comm_Data *data = draindata[i];
        int time = ((data->timestamp.hour()_60 + data->timestamp.minute())*60  + data->timestamp.second()) *1000
                +data->timestamp.msec();
        vars->storagefile<<time<<'\t'<<data->x<<'\t'<<data->y<<'\t'<<data->theta<<'\t'
                        <<data->yaw<<'\t'<<data->leftodom<<'\t'<<data->rightodom<<'\t'<<std::endl;
    }

这两种方法得到的数据结果如下，观察时间戳发现数据有重复：
![screenshot from 2015-04-12 21 33 40](https://cloud.githubusercontent.com/assets/8281407/7105778/4cb10b64-e15c-11e4-8d3e-8cb84ba74849.png)
这个是程序的截图
![screenshot from 2015-04-12 21 35 22](https://cloud.githubusercontent.com/assets/8281407/7105777/4cb11294-e15c-11e4-8c05-6a5c0d202cb9.png)

**Comment by alexanderhmw** [comment]
既然是存数据，为啥BufferSize=10？ @FYKun ，你应该遇到过这种问题

**Comment by alexanderhmw** [comment]
这里再次说明一遍，并配合上内核代码：

```
    QVector<boost::shared_ptr<void> > result;
    int tmpbuffersize=inputparamsbuffer.size();
    if(tmpbuffersize==0)
    {
        return result;
    }
    if(grabSize==0)
    {
        result=QVector<boost::shared_ptr<void> >::fromList(inputparamsbuffer);
        if(inputbuffersize<=0)
        {
            inputparamsbuffer.clear();
        }
        else if(checkstop)
        {
            paramsgrubcount++;
            if(paramsgrubcount>CHECKSTOP*inputbuffersize)
            {
                inputparamsbuffer.clear();
            }
        }
    }
```

当buffersize>0的时候，用grabsize=0去抓取是不会清空buffer的。
当buffersize=0的时候，用grabsize=0去抓取才会清空buffer的。
当然这在RobotSDK_4.0不存在这个问题，因为完全由用户清楚指定数据抓取行为：

```
#ifdef Q_OS_LINUX
#define NUM_0 0b000
#define NUM_1 0b001
#define NUM_2 0b010
#define NUM_3 0b011
#define NUM_4 0b100
#define NUM_5 0b101
#define NUM_6 0b110
#define NUM_7 0b111
#endif

#ifdef Q_OS_WIN
#define NUM_0 0
#define NUM_1 1
#define NUM_2 2
#define NUM_3 3
#define NUM_4 4
#define NUM_5 5
#define NUM_6 6
#define NUM_7 7
#endif

enum ObtainBehavior
{
    CopyOldest=NUM_0,
    GrabOldest=NUM_1,
    CopyLatest=NUM_2,
    GrabLatest=NUM_3,
    CopyOldestStrictly=NUM_4,
    GrabOldestStrictly=NUM_5,
    CopyLatestStrictly=NUM_6,
    GrabLatestStrictly=NUM_7
};
```
